package gcom.observer;

/**
 * Created by timmy on 09/10/16.
 */
public enum ObserverEvent {
    MESSAGE,RECEIVED_MESSAGE,MEMBER_JOINED,MEMBER_HAS_LEFT, CHAT_MESSAGE, ADDING_MEMBER, LEADER_ADD_MEMBER, LEADER_ADD_MEMBER_TO_GROUP, MEMBER_LEFT, MESSAGE_TO_GROUP;
}
